config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  root 'home#index'  
  
  get 'home/index'
  get 'home/show'
  get 'home/about'
  resources :firms
  resources :services
  resources :clients
  resources :downloads
  resources :charges
  
  resources :pages do 
    collection do
      get :clients
      get :services
      get :firms
    end
  end
  
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :firm, optional: true

  validates :service_type, length: { maximum: 100 }, presence: true
  validates :description, length: { maximum: 140 }, presence: true
  validates :price, length: { maximum: 20 }, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
    #@user = session[:userinfo]

  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:service_type, :description, :price)
    end
end

app/helpers/services_helper.rb
# :nocov:
module ServicesHelper
end
# :nocov:

app/views/services/_form.html.erb
  <%= form_with(model: service, local: true) do |form| %>
    <% if service.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

        <ul>
          <% service.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
<body class="bg-light">

  <main>
        <div class="field mb-3">
          <%= form.label :service_type, class:"form-label, lead" %>
          <%= form.text_field :service_type, class:"form-control", placeholder:"e.g. Daily Flat Rate" %>
        </div>

        <div class="field mb-3">
          <%= form.label :description, class:"form-label, lead" %>
          <%= form.text_field :description, class:"form-control", placeholder:"e.g. One investigator, 8 - 10 hours on site" %>
        </div>

        <div class="field mb-3">
          <%= form.label :price, class:"form-label, lead" %>
          <%= form.text_field :price, class:"form-control" %>
        </div>

    <div class="actions mb-3">
      <!-- https://stackoverflow.com/questions/13167535/how-to-put-icon-in-rails-submit-button -->
      <%= button_tag( :class => "bottom-button") do %>
        Save Service <i class="fas fa-paper-plane"></i>
      <% end %>
    </div>
  </main>
</body>
<% end %>

app/views/services/edit.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <h1>Editing Service</h1>
</div>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service, class:"misc-button" %> |
<%= link_to 'Back', services_path, class:"misc-button" %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <h1>Services</h1>
</div>

<!-- https://getbootstrap.com/docs/5.0/content/tables/ -->
<main>
  <table class="table">
    <thead>
      <tr>
        <th>Service Type</th>
        <th>Description</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td data-title="Service Type"><%= service.service_type %></td>
          <td data-title="Description"><%= service.description %></td>
          <td data-title="Price">$<%= service.price %></td>
          <td><%= link_to 'Show', service, class: "show-edit-buttons"%></td>
          <% unless session[:userinfo].nil? %>
            <td><%=  link_to 'Edit', edit_service_path(service), class: "show-edit-buttons" %></td>
            <td><%= link_to 'Destroy', service, class: "destroy-button", method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <%  end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>
<% unless session[:userinfo].nil? %>
  <%=  link_to 'New Service', new_service_path, class:"bottom-button"  %>
<% end %>
<!--Need space for ipad to see the button-->
<br><br><br><br><br>

app/views/services/new.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <h1>New Service</h1>
</div>
<hr class="mb-2">

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path, class:"misc-button" %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron bg-light">
  <br />
  
  <header>
  <h1 class="service-info display-4">
      <strong>Service type:</strong>
      <%= @service.service_type %>
  </h1>
  </header>

  <main>
  <p class="service-info lead">
    <strong>Description:</strong>
    <%= @service.description %> |
    <strong>Price:</strong>
    <%= @service.price %>
    <hr />
  </p>
</main>

  <p class="service-info my-4">
    <%= link_to 'Edit', edit_service_path(@service), class:"misc-button" %> |
    <%= link_to 'Back', services_path, class:"misc-button" %>
  </p>
  <br />
</div>


<!--
<p>
  <strong>Service type:</strong>
  <%= @service.service_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @service.price %>
</p>

<%= link_to 'Edit', edit_service_path(@service), class:"misc-button" %> |
<%= link_to 'Back', services_path, class:"misc-button" %>
-->