config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  root 'home#index'  
  
  get 'home/index'
  get 'home/show'
  get 'home/about'
  resources :firms
  resources :services
  resources :clients
  resources :downloads
  resources :charges
  
  resources :pages do 
    collection do
      get :clients
      get :services
      get :firms
    end
  end
  
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/firm.rb
class Firm < ApplicationRecord
  belongs_to :client, optional: true
  has_and_belongs_to_many :services

  validates :first_name, presence: true, length: { maximum: 60 }
  validates :middle_name, length: { maximum: 60 }
  validates :last_name, presence: true, length: { maximum: 60 }
  validates :maiden_name, length: { maximum: 60 }
  validates :dob,
            format: {with: %r{\A\d{2}-\d{2}-\d{4}\Z}},
            presence: true
  validates :ssn,
            format: {with: %r{\A\d{3}-\d{2}-\d{4}\Z}}
            #,uniqueness: {case_sensitive: false}
  validates :dl_number, length: { maximum: 40 }
  validates :dl_state,
            format: {with: %r{\A\w{2}\Z}}
  validates :notes, length: { maximum: 100 }
  mount_uploader :file, PdfUploader
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController
  before_action :set_firm, only: %i[ show edit update destroy ]
  include Secured
  $grand_total = 0.0
  # GET /firms or /firms.json
  def index
    @services = Service.all
    #@user = session[:userinfo]

    @currentclient = Client.find_by(email: session[:userinfo][:info][:email])
    if @currentclient.nil? and !curr_user_is_admin?
      redirect_to clients_path, notice: "You must fill out the client application in order to create a new request."
    elsif curr_user_is_admin?
      @firms = Firm.all
    else
      @firms = Firm.where(client_id: @currentclient.id)
      @email = session[:userinfo][:info][:email]
      
      total_amount = 0
      @firms.each do |firm|
        if firm.paid == false
          total_amount += firm.total
        else
          next
        end
      end
      @total_price = total_amount
      $grand_total = @total_price
    end
  end

  # GET /firms/1 or /firms/1.json
  def show
  end

  # GET /firms/new
  def new
    @firm = Firm.new
  end

  # GET /firms/1/edit
  def edit
    @services = Service.all
  end

  # POST /firms or /firms.json
  def create
    @firm = Firm.new(firm_params)

    @currentclient = Client.find_by(email: session[:userinfo][:info][:email])
    @firm.client_id = @currentclient[:id]

    # loop through all the services of the current firm record and total the prices
    # and insert it into the total column
    total_amount = 0
    @firm.services.each do |service|
      total_amount += service.price.to_d
   end
   @firm.total = total_amount

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: "Firm was successfully created." }
        format.json { render :show, status: :created, location: @firm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firms/1 or /firms/1.json
  def update
    respond_to do |format|
      if @firm.update(firm_params)
        format.html { redirect_to @firm, notice: "Firm was successfully updated." }
        format.json { render :show, status: :ok, location: @firm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1 or /firms/1.json
  def destroy
    @firm.destroy
    respond_to do |format|
      format.html { redirect_to firms_url, notice: "Firm was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firm
      @firm = Firm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def firm_params
      params.require(:firm).permit(:invoice_data, :first_name, :middle_name, :last_name, :maiden_name, :dob, :ssn, :dl_state, :dl_number, :notes, :client_request, :file, service_ids:[])
    end
end

app/helpers/firms_helper.rb
# :nocov:
module FirmsHelper
end
# :nocov:

app/views/firms/_form.html.erb
  <%= form_with(model: firm, local: true) do |form| %>
    <% if firm.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

        <ul>
          <% firm.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <body class="bg-light">

    <div class="col-lg-6">
      <%= form.label :name, 'Please select services: ' %>
      <br />
      <%= form.collection_check_boxes :service_ids, Service.all, :id, :service_type, unchecked: Service.all.map(&:id) do |b| %>
      <span>
       <%= b.check_box %>
       <%= b.label %>

        <br />
     </span>
      <% end %>
    </div>
    <br>

<!--    <div class="col-md-3 mb-3">-->
      <%#= form.label :invoice_data, class:"form-label" %>
      <%#= form.text_field :invoice_data, class:"form-control" %>
<!--    </div>-->

    <div class="row">

      <div class="col-md-3 mb-3">
        <%= form.label :first_name, class:"form-label" %>
        <%= form.text_field :first_name, class:"form-control", placeholder:"e.g. Robert, Jose, Mohammad" %>
      </div>

      <div class="col-md-3 mb-3">
        <%= form.label :middle_name, class:"form-label" %>
        <%= form.text_field :middle_name, class:"form-control", placeholder:"e.g. enter middle name" %>
      </div>

      <div class="col-md-3 mb-3">
        <%= form.label :last_name, class:"form-label" %>
        <%= form.text_field :last_name, class:"form-control", placeholder:"e.g. enter last name" %>
      </div>

      <div class="col-md-3 mb-3">
        <%= form.label :maiden_name, class:"form-label" %>
        <%= form.text_field :maiden_name, class:"form-control", placeholder:"e.g. enter maiden name" %>
      </div>

    </div>

    <div class="row">

      <div class="col-md-3 mb-3">
        <%= form.label :dob, class:"form-label" %>
        <%= form.text_field :dob, class:"form-control", placeholder:"e.g. 03-16-2001" %>
      </div>

      <div class="col-md-3 mb-3">
        <%= form.label :ssn, class:"form-label" %>
        <%= form.text_field :ssn, class:"form-control", placeholder:"e.g. 334-54-4432" %>
      </div>

      <div class="col-md-3 mb-3">
        <%= form.label :dl_state, class:"form-label" %>
        <%= form.text_field :dl_state, class:"form-control", placeholder:"e.g. CO" %>
      </div>

      <div class="col-md-3 mb-3">
        <%= form.label :dl_number, class:"form-label" %>
        <%= form.text_field :dl_number, class:"form-control", placeholder:"e.g. 65456765" %>
      </div>

    </div>

    <div class="field mb-3">
      <%= form.label :notes, class:"form-label" %>
      <%= form.text_field :notes, class:"form-control", placeholder:"e.g. Provide any additional helpful information." %>
    </div>
    
    <!-- <div class="field mb-3">
      <%= form.label :file, class:"form-label" %>
      <%= form.file_field :file, class:"form-control" %>
    </div> -->

    <hr class="mb-3">

  </body>
    <div class="actions mb-3">
      <%= button_tag( :class => "bottom-button") do %>
        Create Request <i class="fas fa-paper-plane "></i>
      <% end %>
    </div>
 <% end %>

app/views/firms/edit.html.erb
<p id="notice"><%= notice %></p>


<div class="header">
  <h1>Editing Request</h1>
</div>

<%= render 'form', firm: @firm %>

<%= link_to 'Show', @firm, class:"misc-button" %> |
<%= link_to 'Back', firms_path, class:"misc-button" %>

app/views/firms/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header"><h1>Requests</h1>
</div>

<main>
  <table class="table">
    <thead>
      <tr>
        <th>Invoice Data</th>
        <th>Full Name</th>
        <th>DOB</th>
        <th>SSN</th>
        <th>DL State</th>
        <th>DL Number</th>
        <th>Email</th>
        <th>Total</th>
        <th>Paid</th>
        <th>Notes</th>
  <!--      <th>Client Request</th>-->
        <th>Services Requested</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if !@firms.nil? %>
      <% @firms.each do |firm| %>
        <tr>
          <td data-title="Invoice Data" class="view-invoice-cell">
            <%= link_to firm do %>
              View Invoice: <%= firm.id %><br>
            <% end %>
            <%=firm.created_at.strftime("%-m/%d/%y %-I:%M ET")%><br>
            Updated: <%=time_ago_in_words(firm.updated_at)%> ago
          </td>
          <td data-title="Full Name">
            <%= firm.first_name %> <%= firm.middle_name %> <%= firm.last_name %><br>
            Maiden Name: <%= firm.maiden_name %>
          </td>
          <td data-title="DOB" class="dob-ssn-cells"><%= firm.dob %></td>
          <td data-title="SSN" class="dob-ssn-cells"><%= firm.ssn %></td>
          <td data-title="DL State"><%= firm.dl_state %></td>
          <td data-title="DL Number"><%= firm.dl_number %></td>
          <td data-title="Email"><%= @email %></td>
          <td data-title="Total"><%= firm.total %></td>
          <td data-title="Paid"><%= firm.paid %></td>
          <td data-title="Notes"><%= firm.notes %></td>
  <!--        <td><%#= firm.client_request %></td>-->
          <td data-title="Services Requested" class="dob-ssn-cells"><% firm.services.each do |service| %>
              <li><%= service.service_type %> - $<%= service.price %></li>
            <% end %></td>
          <td><%= link_to 'Show', firm, class: "show-edit-buttons"%></td>
          <td><%= link_to 'Edit', edit_firm_path(firm), class: "show-edit-buttons"%></td>
          <td><%= link_to 'Destroy', firm, class: "destroy-button", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</main>

<%= link_to 'New Request', new_firm_path, class:"bottom-button" %>
<!--Need space for ipad to see the button-->

<br><br><br>

<div class="header">
  <h1><a href="/home/index"><img src=<%=asset_path('TalonAgencyLogo.png')%> width="45" height="41" class="d-inline-block align-top"  alt=""></a>
    Talon Agency Checkout</h1>
</div>
<hr style="border: 1px outset #595955;">
<div class="">
  <div class="product">
    <h2>Order Confirmation: </h2>
    <h3>Comprehensive Background Check </h3>
    <h2>$<%= @total_price %></h2>
    <hr style="border: 1px outset #595955;">
    <h3>Total: $<%= @total_price %></h3><% $grand_total = @total_price %>

    <% if $grand_total != 0 %>
      <%= form_tag charges_path do %>
        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
            </article>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-description="Talon Agency Background Check"
                    data-amount="<%@total_price%>"
                    data-label="Buy Now"
                    data-locale="auto">
            </script>
      <% end %>
    <% end %>
  </div>
  <hr style="border: 1px outset #595955;">
  <h2>*** After purchase, please wait for the confirmation page. ***</h2>

</div>

<br><br><br><br><br>

app/views/firms/new.html.erb
<p id="notice"><%= notice %></p>

<div class="header"><h1>New Request</h1>
</div>
<hr class="mb-2">

<%= render 'form', firm: @firm %>

<%= link_to 'Back', firms_path, class:"misc-button" %>
<!--Need space for ipad to see the button-->
<br><br><br><br><br>

app/views/firms/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>-->
<!--  <strong>Invoice Data:</strong>-->
  <%#= @firm.invoice_data %>
<!--</p>-->

<!--<p>-->
<!--  <strong>First Name:</strong>-->
  <%#= @firm.first_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Middle Name:</strong>-->
  <%#= @firm.middle_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Last Name:</strong>-->
  <%#= @firm.last_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Maiden Name:</strong>-->
  <%#= @firm.maiden_name %>
<!--</p>-->

<!--<p>-->
<!--  <strong>DOB:</strong>-->
  <%#= @firm.dob %>
<!--</p>-->

<!--<p>-->
<!--  <strong>SSN:</strong>-->
  <%#= @firm.ssn %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Dl State:</strong>-->
  <%#= @firm.dl_state %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Dl Number:</strong>-->
  <%#= @firm.dl_number %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Notes:</strong>-->
  <%#= @firm.notes %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Client Request:</strong>-->
  <%#= @firm.client_request %>
<!--</p>-->
<main>
<dl class="row">
  <dt class="col-sm-3">Name:</dt>
  <dd class="col-sm-9"><%= @firm.first_name %> <%= @firm.last_name %></dd>
  <dt class="col-sm-3">Invoice Data:</dt>

  <dd class="col-sm-9">
    Invoice: <%= @firm.id %><br>
    Created: <%=@firm.created_at.strftime("%-m/%d/%y, %-I:%M ET")%><br>
    Updated: <%=time_ago_in_words(@firm.updated_at)%> ago</dd>
  <dt class="col-sm-3">DOB:</dt>
  <dd class="col-sm-9"><%= @firm.dob %></dd>
  <dt class="col-sm-3">SSN:</dt>
  <dd class="col-sm-9"><%= @firm.ssn %></dd>
  <dt class="col-sm-3">DL State:</dt>
  <dd class="col-sm-9"><%= @firm.dl_state %></dd>
  <dt class="col-sm-3">DL Number:</dt>
  <dd class="col-sm-9"><%= @firm.dl_number %></dd>
  <dt class="col-sm-3">Notes:</dt>
  <dd class="col-sm-9"><%= @firm.notes %></dd>
<!--  <dt class="col-sm-3">Client Request:</dt>-->
<!--  <dd class="col-sm-9"><%#= @firm.client_request %></dd>-->
  <dt class="col-sm-3">Services:</dt>
  <dd class="col-sm-9">
    <% @firm.services.each do |service| %>
      <li><%= service.service_type %> - <%= service.price %></li>
    <% end %>
  </dd>
</dl>
</main>

<%= link_to 'Edit', edit_firm_path(@firm), class:"misc-button" %> |
<%= link_to 'Back', firms_path, class:"misc-button" %>