config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  root 'home#index'  
  
  get 'home/index'
  get 'home/show'
  get 'home/about'
  resources :firms
  resources :services
  resources :clients
  resources :downloads
  resources :charges
  
  resources :pages do 
    collection do
      get :clients
      get :services
      get :firms
    end
  end
  
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :firms

  validates :client_name, length: { maximum: 40 }, presence: true
  validates :company, length: { maximum: 60 }
  validates :address, length: { maximum: 100 }
  validates :city, length: { maximum: 40 }
  validates :state,
            format: {with: %r{\A\w{2}\Z}}
  validates :zip,
            format: {with: %r{\A\d{5}\Z}}
  validates :phone,
            format: {with: %r{\A\d{3}-\d{3}-\d{4}\Z}}
  validates :fax,
            format: {with: %r{\A\d{3}-\d{3}-\d{4}\Z}}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP },
            #presence: true,
            length: {maximum: 40},
            uniqueness: {case_sensitive: false}
  validates :notes, length: { maximum: 140 }
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  include Secured

  # NOTE
  # FIXME: Find a different way to keep track of admin (maybe via an admin table so the
  # current admin can add more on the view)

  # GET /clients or /clients.json
  def index
    @admin = "talontest7@gmail.com"
    if curr_user_is_admin?
      @clients = Client.all
    else
      @currentclient = Client.find_by(email: session[:userinfo][:info][:email])
    end
  end

  # GET /clients/1 or /clients/1.json
  def show
    @currentclient = Client.find_by(email: session[:userinfo][:info][:email])
    if curr_user_is_admin?
      render :show
    elsif !session[:userinfo].nil? && !@currentclient.nil? && session[:userinfo][:info][:email] == @currentclient.email
      @client = Client.find_by(email: session[:userinfo][:info][:email])
      render :show
    else
      redirect_to clients_path
    end
  end

  # GET /clients/new
  def new
    @client = Client.new :email => session[:userinfo][:info][:email]
    @admin = "talontest7@gmail.com"

  end

  # GET /clients/1/edit
  def edit
    @admin = "talontest7@gmail.com"
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      # if the current user is not an admin and they try to change the status, it doesn't get processed
      if !curr_user_is_admin?
        params.require(:client).permit(:client_name, :status, :total_requests, :company, :email, :address, :city, :state, :zip, :phone, :fax, :notes, :client_id).delete_if do |key, val|
          key == "status"
        end
      else
        params.require(:client).permit(:client_name, :status, :total_requests, :company, :email, :address, :city, :state, :zip, :phone, :fax, :notes, :client_id)
      end
    end
end

app/helpers/clients_helper.rb
# :nocov:
module ClientsHelper
end
# :nocov:

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--Form inspired by: https://getbootstrap.com/docs/4.0/examples/checkout/ -->
  <body class="bg-light">

  <!--    <header>-->
  <!--    <div class="container">-->
  <!--      <div class="py-5 text-center">-->
  <!--        <h1>New Client</h1>-->
  <!--        <p class="lead">New Client Form</p>-->
  <!--      </div>-->
  <!--    </div>-->
  <!--    </header>-->

  <main class="talon-input-field">

    <div class="row">
      <div class="col-md-3 mb-3">
        <%= form.label :client_name, class:"form-label" %>
        <%= form.text_field :client_name, type: 'text', class: 'form-control', placeholder:"e.g. Jesse, Xiasong, Edgar"%>
      </div>

      <div class="col-md-3 mb-3">
        <%= form.label :email, class:"form-label" %>
        <%= form.text_field :email, class:"form-control",:readonly => true %>
      </div>
      <div class="col-md-3 mb-3">
        <%= form.label :company, class:"form-label" %>
        <%= form.text_field :company, type: 'text', class: 'form-control', placeholder:"e.g. Herbie's Used Cars"%>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 mb-3">
        <%= form.label :phone, class:"form-label" %>
        <%= form.text_field :phone, type: 'text', class: 'form-control', placeholder:"e.g. 722-755-1234"%>
      </div>
      <div class="col-md-3 mb-3">
        <%= form.label :fax, class:"form-label" %>
        <%= form.text_field :fax, type: 'text', class: 'form-control', placeholder:"e.g. 504-987-1235"%>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 mb-3">
        <%= form.label :address, class:"form-label" %>
        <%= form.text_field :address, type: 'text', class: 'form-control', placeholder:"e.g. 4629 Rosedale Dr."%>
      </div>
      <div class="col-md-3 mb-3">
        <%= form.label :city, class:"form-label" %>
        <%= form.text_field :city, type: 'text', class: 'form-control', placeholder:"e.g. Denver"%>
      </div>
      <div class="col-md-1 mb-3">
        <%= form.label :state, class:"form-label" %>
        <%= form.text_field :state, type: 'text', class: 'form-control', placeholder:"CO"%>
      </div>
      <div class="col-md-2 mb-3">
        <%= form.label :zip, class:"form-label" %>
        <%= form.text_field :zip, type: 'text', class: 'form-control', placeholder:"e.g. 80231"%>
      </div>
    </div>

<!--    <div class="row">-->
<!--      <div class="col-md-1 mb-3" style="white-space: nowrap">-->
<!--        <%#= form.label :client_id, class:"form-label" %> ID-->
        <%#= form.number_field :client_id, class: 'form-control'%>
<!--      </div>-->
<!--      <div class="col-md-1 mb-3" style="white-space: nowrap">-->
        <%#= form.label :total_requests, class:"form-label" %>
        <%#= form.number_field :total_requests, class: 'form-control' %>
<!--      </div>-->
<!--    </div>-->


    <div class="row">
      <div class="col-md-8 mb-3">
        <%= form.label :notes, class:"form-label" %>
        <%= form.text_field :notes, class: 'form-control', placeholder:"e.g. Provide any important information." %>
      </div>
    </div>
    <% if session[:userinfo][:info][:email] == @admin %>
      <h4 class="mb-3">Administrator: Check mark the Activate box to enable Client Requests.</h4>
      <div class="col-md-4 mb-3">
        <%= form.check_box :status %>
        <%= form.label :activate, class:"form-label" %>
      </div>
    <% end %>

    <hr class="mb-3">

  </main>
  </body>
  <div class="actions mb-3">
    <!-- https://stackoverflow.com/questions/13167535/how-to-put-icon-in-rails-submit-button -->
    <%= button_tag( :class => "bottom-button") do %>
      Save Client <i class="fas fa-paper-plane"></i>
    <% end %>
    <!-- <%= form.submit class:"btn btn-primary" %>
      <i class="fas fa-paper-plane"></i> -->
  </div>
<% end %>

app/views/clients/edit.html.erb
<p id="notice"><%= notice %></p>


<div class="header">
  <h1>Editing Client</h1>
</div>
<%= render 'form', client: @client %>

<%= link_to 'Show', @client, class:"misc-button" %> |
<%= link_to 'Back', clients_path, class:"misc-button" %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="header"><h1>Clients</h1>
</div>

<main>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Client Name </th>
      <th scope="col">Company </th>
      <th scope="col" class="email-header">Email </th>
      <th scope="col">Phone </th>
      <th scope="col">Fax </th>
      <th scope="col">Address </th>
      <th scope="col">City </th>
      <th scope="col">State </th>
      <th scope="col">Zip </th>
      <th class="client-id-header" scope="col">Client ID </th>
      <th scope="col">Notes </th>
      <th scope="col">Status </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% if session[:userinfo][:info][:email] == @admin %>
      <% @clients.each do |client| %>
        <tr>
          <td data-title="Client Name"><%= client.client_name %></td>
          <td data-title="Company"><%= client.company %></td>
          <td data-title="Email" class="email-cell"><%= client.email %></td>
          <td data-title="Phone" class="phone-fax-cell"><%= client.phone %></td>
          <td data-title="Fax" class="phone-fax-cell"><%= client.fax %></td>
          <td data-title="Address"><%= client.address %></td>
          <td data-title="City"><%= client.city %></td>
          <td data-title="State"><%= client.state %></td>
          <td data-title="Zip"><%= client.zip %></td>
          <td data-title="Client ID"><%= client.id %></td>
          <td data-title="Notes"><%= client.notes %></td>
          <td data-title="Status"><%= client.status%></td>
          <!--        <td><%#= client.status ? "active" : "inactive"%></td>-->
  <!--        <td><%#= client.total_requests %></td>-->
          <td><%= link_to 'Show', client, class: "show-edit-buttons"%></td>
          <td><%= link_to 'Edit', edit_client_path(client), class: "show-edit-buttons"%></td>
          <td><%= link_to 'Destroy', client, class: "destroy-button", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
        <% if !@currentclient.nil? %>
          <tr>
            <td><%= @currentclient.client_name %></td>
            <td><%= @currentclient.company %></td>
            <td class="email-cell"><%= @currentclient.email %></td>
            <td class="phone-fax-cell"><%= @currentclient.phone %></td>
            <td class="phone-fax-cell"><%= @currentclient.fax %></td>
            <td><%= @currentclient.address %></td>
            <td><%= @currentclient.city %></td>
            <td><%= @currentclient.state %></td>
            <td><%= @currentclient.zip %></td>
            <td><%= @currentclient.id %></td>
            <td><%= @currentclient.notes %></td>
            <td><%= @currentclient.status%></td>
            <!--        <td><%#= client.status ? "active" : "inactive"%></td>-->
    <!--        <td><%#= client.total_requests %></td>-->
            <td><%= link_to 'Show', @currentclient, class: "show-edit-buttons"%></td>
            <td><%= link_to 'Edit', edit_client_path(@currentclient), class: "show-edit-buttons"%></td>
            <td><%= link_to 'Destroy', @currentclient, class: "destroy-button", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>
</main>

<%= link_to 'New Client', new_client_path, :class => "bottom-button" %>
<!--Need space for ipad to see the button-->
<br><br><br><br><br>

app/views/clients/new.html.erb
<p id="notice"><%= notice %></p>

<div class="header">
  <h1>New Client</h1>
</div>
<hr class="mb-2">

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path, class:"misc-button" %>
<!--Need space for ipad to see the button-->
<br><br><br><br><br>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<main>
<p>
  <strong>Client name:</strong>
  <%= @client.client_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @client.status %>
</p>

<!--<p>-->
<!--  <strong>Total requests:</strong>-->
  <%#= @client.total_requests %>
<!--</p>-->

<p>
  <strong>Company:</strong>
  <%= @client.company %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @client.fax %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<p>
  <strong>Client ID:</strong>
  <%= @client.id %>
</p>
</main>

<%= link_to 'Edit', edit_client_path(@client), class:"misc-button"  %> |
<%= link_to 'Back', clients_path, class:"misc-button"  %>