config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  root 'home#index'  
  
  get 'home/index'
  get 'home/show'
  get 'home/about'
  resources :firms
  resources :services
  resources :clients
  resources :downloads
  resources :charges
  
  resources :pages do 
    collection do
      get :clients
      get :services
      get :firms
    end
  end
  
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'logout#logout'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@user = session[:userinfo]
  end

  def show
    #@user = session[:userinfo]
  end

  def about
  end
end

app/helpers/home_helper.rb
# :nocov:
module HomeHelper
end
# :nocov:

app/views/home/_footer.html.erb
<div class="footer mt-5">
  <p>© Talon Agency, LLC | P.O. Box 73502 | Metairie, LA 70033-3502 | 1-800-501-3256 | info@talonagency.com</p>
</div>

app/views/home/_navbar.html.erb
<div>
  <nav class="navbar navbar-expand-lg navbar-custom shadow">
    <div class="container-fluid" >
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <i class="bi bi-justify"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav me-auto">
          <a href="/"><img src=<%=asset_path('TalonAgencyLogo.png')%> width="45" height="41" class="nav-image d-inline-block align-top" alt=""></a>
          <a class="nav-item navbar-element mr-auto" href="<%= services_path %>">Services</a>
          <% unless session[:userinfo].nil? %>
            <a class="nav-item navbar-element" href="<%= firms_path %>">Requests</a>
            <a class="nav-item navbar-element" href="<%= clients_path %>">Clients</a>
            <a class="nav-item navbar-element" href="<%= downloads_path %>">Downloads</a>
          <% end %>
        </div>
      </div>
    </div>
    <a id="navbar-about" class="nav-item navbar-about" href="/home/about">About</a>
    <div class="navbar-nav ms-auto">
      <% if !session[:userinfo].nil? %>
        <div class="dropdown show">
          <a class="navbar-profile-dropdown-btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle"></i>
            <% if session[:userinfo].extra.raw_info.given_name == nil %>
              Account
            <% else %>
              <%= session[:userinfo].extra.raw_info.given_name %> <!-- change this to be first name eventually? -->
            <% end %>
          </a>
          <div class="dropdown-menu navbar-dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="/home/show">Account</a>
            <a class="dropdown-item" href="/logout">Logout</a>
          </div>
        </div>
      <% else %>
        <%= link_to 'Login', 'auth/auth0', method: :post, id: 'navbar-login', class: 'nav-item navbar-login', 'aria-current' => "page" %>
      <% end %>
    </div>
  </nav>
</div>

app/views/home/about.html.erb
<p id="notice"><%= notice %></p>

<div class="header"><h1>About</h1>
</div>

<hr class="divider">



<section class="header  text-center">
  <h2>TalonAgency.com Design Team</h2>
</section>

<div class="container">
  <div class="row">
    <div class="col col-md-6"><div class="panel panel-default">
      <div class="panel-heading">Dominick Licciardi</div>
      <div class="profile-title">Developer</div>
      <%= image_tag("placeholder-profile.jpg", :alt => "Placeholder", :class => "profile-pictures") %>
      <div class="social-icon-container">
    <a href="https://www.linkedin.com/in/dominicklicciardi"><i class="profile-social-icons bi bi-linkedin"></i></a>
    <a href="https://github.com/DominickNola"><i class="profile-social-icons bi bi-github"></i></a>
</div>
      <p class="profile-info"> Computer Science - MSU 2021 <br> Web-App | Network Security | Machine Learning <br>
    </div></div>

    <div class="col col-md-6"><div class="panel panel-default">
      <div class="panel-heading">Warren Ramos</div>
      <div class="profile-title">Developer</div>
      <%= image_tag("warren-profile.jpg", :alt => "Warren' Image", :class => "profile-pictures") %>
      <div class="social-icon-container">
        <a href="https://www.linkedin.com/in/warren-joseph-ramos"><i class="profile-social-icons bi bi-linkedin"></i></a>
        <a href="https://github.com/WarrenJRamos"><i class="profile-social-icons bi bi-github"></i></a>
</div>
      <p class="profile-info">Warren is a curious student, seeking edification in full stack development through his first major web app project, Talon Agency. He assisted the front-end, back-end, and testing teams with a focus on developing strategies for overcoming blockers and integrating new functionality. He is graduating on May 14, 2021, and plans to get certified in full stack development before landing a job in the field of web development.</p>

    </div></div>

    <div class="col col-md-6"><div class="panel panel-default">
      <div class="panel-heading">Jose Velasquez</div>
      <div class="profile-title">Developer</div>
      <%= image_tag("jose-profile.jpg", :alt => "Jose Image", :class => "profile-pictures") %>
      <div class="social-icon-container">
        <a href="https://www.linkedin.com/in/jose-velasquez-dev"><i class="profile-social-icons bi bi-linkedin"></i></a>
        <a href="https://github.com/josevdevr"><i class="profile-social-icons bi bi-github"></i></a>
</div>
      <p class="profile-info">Jose is in his senior year at Metropolitan State University and will graduate Spring 2021 with a bachelors degree in Computer Science. As part of both the backend and front-end teams, he helped with meeting sprint objectives and goals. His favorite part of working on the Talon Agency Project was working with and learning from other fellow team members. Jose is looking to pursue a career in web development after graduation</p>
    </div></div>

    <div class="col col-md-6"><div class="panel panel-default">
      <div class="panel-heading">Grant Schumacher</div>
      <div class="profile-title">Developer</div>
      <%= image_tag("Grant-profile.png", :alt => "Grant Image", :class => "profile-pictures") %>
      <div class="social-icon-container">
        <a href="https://www.linkedin.com/in/grant-schumacher"><i class="profile-social-icons bi bi-linkedin"></i></a>
        <a href="https://github.com/GrantSchumacher"><i class="profile-social-icons bi bi-github"></i></a>
</div>
      <p class="profile-info">Grant is graduating from MSU Denver spring 2021. He enjoys front end web development, and finds fulfillment in delivering consistent, creative designs and user experiences on the web. His contributions to Talon Agency were in front end design and implementation, user experience, testing, and contributions to the backend. Grant plans on pursuing a career in front end web development after graduation.</p>
    </div></div>

    <div class="col col-md-6"><div class="panel panel-default">
      <div class="panel-heading">Stuart Griffin</div>
      <div class="profile-title">Developer</div>
      <%= image_tag("placeholder-profile.jpg", :alt => "Placeholder", :class => "profile-pictures") %>
      <div class="social-icon-container">
        <a href="https://www.linkedin.com/in/stuart-griffin-54a7a7116"><i class="profile-social-icons bi bi-linkedin"></i></a>
        <a href="https://github.com/griff8434"><i class="profile-social-icons bi bi-github"></i></a>
</div>
      <p class="profile-info"> Computer Science - MSU 2021 <br> Penetration Testing | Dark Web Exploration <br>
    </div></div>

    <div class="col col-md-6"><div class="panel panel-default">
      <div class="panel-heading">Mohammad Mansoor</div>
      <div class="profile-title">Developer</div>
      <%= image_tag("muhammad-profile.jpg", :alt => "Muhammad Image", :class => "profile-pictures") %>
      <div class="social-icon-container">
        <a href="https://www.linkedin.com/in/mohammad-mansoor-875678197"><i class="profile-social-icons bi bi-linkedin"></i></a>
        <a href="https://github.com/mmansoo1"><i class="profile-social-icons bi bi-github"></i></a>
</div>
      <p class="profile-info">Mohammad is currently a senior at MSU Denver graduating in May 2021 with a Bachelor's in Computer Science. As part of the frontend team, Mohammad helped shaped the overall UI of the website and made it a responsive experience for all users. After graduation, he plans to pursue a career in software engineering and add to his skills as a web developer.</p>
    </div></div>

    <div class="col col-md-6"><div class="panel panel-default">
      <div class="panel-heading">Ian Mutahi</div>
      <div class="profile-title">Developer</div>
      <%= image_tag("ian-profile.jpg", :alt => "Ian Profile", :class => "profile-pictures") %>
      <div class="social-icon-container">
        <a href="https://www.linkedin.com/in/ian-mutahi-759b39185r"><i class="profile-social-icons bi bi-linkedin"></i></a>
        <a href="https://github.com/imutahi"><i class="profile-social-icons bi bi-github"></i></a>
</div>
      <p class="profile-info">Ian is a Senior at MSU Denver graduating in May 2021 with a Bachelors in Computer Science. As part of both the front end and the back end teams, Ian worked with the team to collectively meet the required goals for our Sprints. After graduation, he plans to pursue a career in Software Engineering</p>
    </div></div>
</div>
</div>

<hr class="divider">

app/views/home/show.html.erb
<h1>User Profile</h1>
<% if !session[:userinfo].nil? %>
    <!-- Auth0 token-->
    <!-- <%= session[:userinfo].inspect %> -->
    <!-- AUTH0 User Profile -->
    <section class="jumbotron  text-center">
      <h2><img class="jumbo-thumbnail img-circle" src="<%= session[:userinfo][:info][:image] %>"/></h2>
      <h2>Welcome, <%= session[:userinfo][:info][:name] %></h2>
    </section>
    <section class="container">
      <div class="panel panel-default">
        <div class="panel-heading">Normalized User Profile</div>
        <div class="panel-body">
          <pre><%= JSON.pretty_generate(session[:userinfo][:info]) %></pre>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">Full User Profile</div>
        <div class="panel-body">
          <pre><%= JSON.pretty_generate(session[:userinfo][:extra][:raw_info]) %></pre>
        </div>
      </div>
    </section>
<% end %>